// config.js — auto-generated by openapi-test-gen
// Override BASE_URL at runtime via the BASE_URL environment variable
// without needing to regenerate tests (e.g. BASE_URL=https://staging.api.com npm test)

export const BASE_URL = process.env.BASE_URL ?? 'https://petstore3.swagger.io/api/v3';
