// endpoints.js — auto-generated by openapi-test-gen

export const ENDPOINTS = Object.freeze({
  addPet: { method: 'POST', path: '/pet' },
  updatePet: { method: 'PUT', path: '/pet' },
  findPetsByStatus: { method: 'GET', path: '/pet/findByStatus' },
  findPetsByTags: { method: 'GET', path: '/pet/findByTags' },
  getPetById: { method: 'GET', path: '/pet/{petId}' },
  updatePetWithForm: { method: 'POST', path: '/pet/{petId}' },
  deletePet: { method: 'DELETE', path: '/pet/{petId}' },
  uploadFile: { method: 'POST', path: '/pet/{petId}/uploadImage' },
  getInventory: { method: 'GET', path: '/store/inventory' },
  placeOrder: { method: 'POST', path: '/store/order' },
  getOrderById: { method: 'GET', path: '/store/order/{orderId}' },
  deleteOrder: { method: 'DELETE', path: '/store/order/{orderId}' },
  createUser: { method: 'POST', path: '/user' },
  createUsersWithListInput: { method: 'POST', path: '/user/createWithList' },
  loginUser: { method: 'GET', path: '/user/login' },
  logoutUser: { method: 'GET', path: '/user/logout' },
  getUserByName: { method: 'GET', path: '/user/{username}' },
  updateUser: { method: 'PUT', path: '/user/{username}' },
  deleteUser: { method: 'DELETE', path: '/user/{username}' }
});
