// pet.test.js — auto-generated by openapi-test-gen

import { describe, it, expect } from 'vitest';
import { BASE_URL } from './config.js';
import { ENDPOINTS } from './endpoints.js';
import * as validators from './validators.js';

describe('addPet', () => {
  // TODO: Body fields: id, name, category, photoUrls, tags, status
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.addPet.path}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateAddPet(body);
    expect(validators.validateAddPet.errors).toBeNull();
  });
});

describe('updatePet', () => {
  // TODO: Body fields: id, name, category, photoUrls, tags, status
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.updatePet.path}`, {
      method: 'PUT',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateUpdatePet(body);
    expect(validators.validateUpdatePet.errors).toBeNull();
  });
});

describe('findPetsByStatus', () => {
  // TODO: Query params: status
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.findPetsByStatus.path}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateFindPetsByStatus(body);
    expect(validators.validateFindPetsByStatus.errors).toBeNull();
  });
});

describe('findPetsByTags', () => {
  // TODO: Query params: tags
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.findPetsByTags.path}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateFindPetsByTags(body);
    expect(validators.validateFindPetsByTags.errors).toBeNull();
  });
});

describe('getPetById', () => {
  // TODO: Path params: petId
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.getPetById.path.replace('{petId}', 'PLACEHOLDER_PETID')}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateGetPetById(body);
    expect(validators.validateGetPetById.errors).toBeNull();
  });
});

describe('updatePetWithForm', () => {
  // TODO: Path params: petId | Query params: name, status
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.updatePetWithForm.path.replace('{petId}', 'PLACEHOLDER_PETID')}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateUpdatePetWithForm(body);
    expect(validators.validateUpdatePetWithForm.errors).toBeNull();
  });
});

describe('deletePet', () => {
  // TODO: Path params: petId
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.deletePet.path.replace('{petId}', 'PLACEHOLDER_PETID')}`, {
      method: 'DELETE',
    });
    expect(response.ok).toBe(true);
  });
});

describe('uploadFile', () => {
  // TODO: Path params: petId | Query params: additionalMetadata
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.uploadFile.path.replace('{petId}', 'PLACEHOLDER_PETID')}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateUploadFile(body);
    expect(validators.validateUploadFile.errors).toBeNull();
  });
});
