// store.test.js — auto-generated by openapi-test-gen

import { describe, it, expect } from 'vitest';
import { BASE_URL } from './config.js';
import { ENDPOINTS } from './endpoints.js';
import * as validators from './validators.js';

describe('getInventory', () => {
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.getInventory.path}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateGetInventory(body);
    expect(validators.validateGetInventory.errors).toBeNull();
  });
});

describe('placeOrder', () => {
  // TODO: Body fields: id, petId, quantity, shipDate, status, complete
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.placeOrder.path}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validatePlaceOrder(body);
    expect(validators.validatePlaceOrder.errors).toBeNull();
  });
});

describe('getOrderById', () => {
  // TODO: Path params: orderId
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.getOrderById.path.replace('{orderId}', 'PLACEHOLDER_ORDERID')}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateGetOrderById(body);
    expect(validators.validateGetOrderById.errors).toBeNull();
  });
});

describe('deleteOrder', () => {
  // TODO: Path params: orderId
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.deleteOrder.path.replace('{orderId}', 'PLACEHOLDER_ORDERID')}`, {
      method: 'DELETE',
    });
    expect(response.ok).toBe(true);
  });
});
