// user.test.js — auto-generated by openapi-test-gen

import { describe, it, expect } from 'vitest';
import { BASE_URL } from './config.js';
import { ENDPOINTS } from './endpoints.js';
import * as validators from './validators.js';

describe('createUser', () => {
  // TODO: Body fields: id, username, firstName, lastName, email, password, phone, userStatus
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.createUser.path}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateCreateUser(body);
    expect(validators.validateCreateUser.errors).toBeNull();
  });
});

describe('createUsersWithListInput', () => {
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.createUsersWithListInput.path}`, {
      method: 'POST',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateCreateUsersWithListInput(body);
    expect(validators.validateCreateUsersWithListInput.errors).toBeNull();
  });
});

describe('loginUser', () => {
  // TODO: Query params: username, password
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.loginUser.path}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateLoginUser(body);
    expect(validators.validateLoginUser.errors).toBeNull();
  });
});

describe('logoutUser', () => {
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.logoutUser.path}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
  });
});

describe('getUserByName', () => {
  // TODO: Path params: username
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.getUserByName.path.replace('{username}', 'PLACEHOLDER_USERNAME')}`, {
      method: 'GET',
    });
    expect(response.ok).toBe(true);
    const body = await response.json();
    validators.validateGetUserByName(body);
    expect(validators.validateGetUserByName.errors).toBeNull();
  });
});

describe('updateUser', () => {
  // TODO: Path params: username | Body fields: id, username, firstName, lastName, email, password, phone, userStatus
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.updateUser.path.replace('{username}', 'PLACEHOLDER_USERNAME')}`, {
      method: 'PUT',
    });
    expect(response.ok).toBe(true);
  });
});

describe('deleteUser', () => {
  // TODO: Path params: username
  it('returns 2xx on happy path', async () => {
    const response = await fetch(`${BASE_URL}${ENDPOINTS.deleteUser.path.replace('{username}', 'PLACEHOLDER_USERNAME')}`, {
      method: 'DELETE',
    });
    expect(response.ok).toBe(true);
  });
});
